version: "3.8"

services:
  helmes-pg:
    image: postgres:17
    container_name: helmes-pg
    environment:
      POSTGRES_DB: my-db
      POSTGRES_USER: psuser
      POSTGRES_PASSWORD: pspass
    ports:
      - "6001:5432"
    volumes:
      - postgres_data:/var/lib/helmes-pg/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U psuser -d my-db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
