server:
  port: 4000
  servlet:
    session:
      timeout: 3600s
      cookie:
        max-age: 3600
        http-only: true
        secure: false
        same-site: lax

logging:
  level:
    ROOT: INFO
    com.kzree.backend: DEBUG

spring:
  application:
    name: my-api
  jackson:
    serialization:
      write-dates-as-timestamps: false

  devtools:
    livereload:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:6001/my-db
    username: psuser
    password: pspass
    hikari:
      pool-name: PostgresHikari
      auto-commit: false
  flyway:
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:6001/my-db
    user: psuser
    password: pspass
