logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    com.kzree.backend: DEBUG

spring:
  datasource:
    url: jdbc:tc:postgresql:latest///my-db
    username: user
    password: user
    hikari:
      pool-name: PostgresHikari
      auto-commit: false
